version: '3'
services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio-docker-local
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
      - './plugins:/verdaccio/pulgins'
volumes:
  verdaccio:
    driver: local