version: '3'
services:
  nginx:
    # TODO 打包镜像和运行容器最好是分开进行
    # build: ./nginx
    image: nginx:v1
    # links:
    #   - nodejs:nodejs
    depends_on:
      - nodejs
      - nodejs1
      - nodejs2
    volumes:
      - ./nginx/app:/apps/
      - ./nginx/conf:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "9000:9000"
  nodejs:
    # 同上
    # build: ./node
    image: node:v1
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
  nodejs1:
    # build: ./node
    image: node:v1
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
  nodejs2:
    # build: ./node
    image: node:v1
    ports:
      - "8082:8082"
    environment:
      - PORT=8082