version: '3'
services:
  nginx:
    # TODO 打包镜像和运行容器最好是分开进行
    build: ./nginx
    # links:
    #   - nodejs:nodejs
    depends_on:
      - nodejs
      - nodejs1
      - nodejs2
    volumes:
      - ./nginx/app:/apps/
      - ./nginx/conf:/etc/nginx/conf.d/
    ports:
      - "80:80"
  nodejs:
    # 同上
    build: ./node
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
  nodejs1:
    build: ./node
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
  nodejs2:
    build: ./node
    ports:
      - "8082:8082"
    environment:
      - PORT=8082